import type { XmasQuestion } from "@/types/game";

export const QUESTIONS: XmasQuestion[] = [
  {
    id: "q1",
    prompt: "You show up to the holiday party already late. What is your excuse?",
    options: ["Stuck in a chimney crawlspace", "Got lost in a mall parking lot", "I was busy saving a reindeer", "Detoured for a mistletoe kiss"],
    imagePrompt: "A person in a Santa suit stuck halfway down a brick chimney, legs kicking in the air, comic book style, cozy winter night lighting.",
    imageSide: "left",
  },
  {
    id: "q2",
    prompt: "Pick your preferred holiday snack.",
    options: ["Peppermint bark with attitude", "A suspiciously festive fruitcake", "Cold pizza in a Santa hat", "Hot cocoa with marshmallows and a wink"],
    imagePrompt: "A suspiciously glowing, dense fruitcake with small festive decorations, moody dramatic lighting, hand-drawn illustration style.",
    imageSide: "right",
  },
  {
    id: "q3",
    prompt: "Your gift wrapping style is best described as...",
    options: ["Beautiful chaos and tape", "Minimalist, borderline threatening", "I don’t wrap. I haunt.", "Soft paper, twine bow, candlelit vibes"],
    imagePrompt: "A gift wrapped in way too much tape and mismatched colorful paper, chaotic but festive, hand-drawn Peanuts-style illustration.",
    imageSide: "left",
  },
  {
    id: "q4",
    prompt: "Someone puts on carols. Your move?",
    options: ["Sing too loud on purpose", "Lip sync and judge quietly", "Swap it for ominous bells", "Sway slow and sing the harmonies"],
    imagePrompt: "A pair of large, antique brass church bells hanging in a snowy belfry at night, dramatic shadows, winter atmosphere.",
    imageSide: "right",
  },
  {
    id: "q5",
    prompt: "You find a list labeled ‘Naughty.’ What do you do?",
    options: ["Update it with receipts", "Pretend you never saw it", "Add my own name for sport", "Fold it up and mind my business"],
    imagePrompt: "A thick parchment scroll labeled 'NAUGHTY' in big red letters, lying on a wooden table next to a flickering candle and a quill.",
    imageSide: "left",
  },
  {
    id: "q6",
    prompt: "Choose your holiday transportation.",
    options: ["Sleigh with questionable safety", "Snowmobile with fake antlers", "Public transit, but it’s haunted", "Horse-drawn carriage, slow and cozy"],
    imagePrompt: "A vintage red sleigh with mismatched wooden planks and a loose runner, sitting alone in deep snow under a moonlit sky.",
    imageSide: "right",
  },
  {
    id: "q7",
    prompt: "What’s your role in group photo time?",
    options: ["Center stage, obviously", "Side-eye in the back row", "Photobomb from the shadows", "Hold hands with whoever looks cold"],
    imagePrompt: "A group of festive people posing for a photo, with one person as a mysterious shadowy figure with glowing eyes in the back row.",
    imageSide: "left",
  },
  {
    id: "q8",
    prompt: "A child asks if you’re Santa. You reply…",
    options: ["Ho ho... maybe", "Absolutely not, move along", "I’m Santa’s HR", "Only on weekends, kiddo"],
    imagePrompt: "A small child looking up in awe at a person in a corporate suit wearing a tiny, crooked Santa hat, high contrast lighting.",
    imageSide: "right",
  },
  {
    id: "q9",
    prompt: "Pick a holiday smell.",
    options: ["Cinnamon, pine, mild panic", "Burnt sugar and regret", "Wet wool and mystery", "Vanilla, orange peel, fireplace smoke"],
    imagePrompt: "A steaming mug of spiced cider sitting next to a pile of wet, woolly mittens on a rustic wooden bench.",
    imageSide: "left",
  },
  {
    id: "q10",
    prompt: "You’ve been tasked with decorating the tree. You...",
    options: ["Create a glitter explosion", "Hang one ornament and leave", "Replace the star with a skull", "Hang the heartfelt ornament and pour a cocoa"],
    imagePrompt: "A Christmas tree where the top star has been replaced by a small, festive, white skull, twinkling lights in the background.",
    imageSide: "right",
  },
  {
    id: "q11",
    prompt: "The office Secret Santa is happening. Your strategy?",
    options: ["Overdeliver, become legend", "Regift like a pro", "Forget the date, improvise", "Handmade and heartfelt"],
    imagePrompt: "A poorly wrapped box with a 'To: Secret Santa' tag, sitting lonely on a messy office desk after everyone has left.",
    imageSide: "left",
  },
  {
    id: "q12",
    prompt: "Which holiday movie energy do you embody?",
    options: ["Chaotic heartwarming montage", "Brooding misunderstood villain", "Animated chaos with a moral", "Soft rom-com with a snowy kiss"],
    imagePrompt: "A split-screen view: one side shows a heartwarming cozy fireplace, the other shows a brooding figure in a dark holiday cloak.",
    imageSide: "right",
  },
  {
    id: "q13",
    prompt: "Pick a holiday pet.",
    options: ["Reindeer with attitude", "Overcaffeinated elf dog", "Silent snow owl", "Sleepy lap cat in a tiny sweater"],
    imagePrompt: "A majestic snow owl with a tiny red scarf perched on a frosted pine branch, soft winter snowflakes falling.",
    imageSide: "left",
  },
  {
    id: "q14",
    prompt: "A snowball fight breaks out. You...",
    options: ["Lead the charge", "Build a tactical fort", "Disappear, reappear elsewhere", "Ref on the sidelines with hot chocolate"],
    imagePrompt: "A massive, tactical snow fort with multiple levels and a flag made from an old holiday sweater.",
    imageSide: "right",
  },
  {
    id: "q15",
    prompt: "Someone says ‘holiday cheer.’ Your reaction?",
    options: ["Pour it into a mug", "Nod politely", "Ask for a refund", "Toast to it and smile"],
    imagePrompt: "An empty glass mug with a few drops of eggnog and a single peppermint stick leaning against the rim, lonely setting.",
    imageSide: "left",
  },
  {
    id: "q16",
    prompt: "Your stocking is filled with...",
    options: ["Glitter, snacks, chaos", "A single ominous bell", "A note that just says ‘soon’", "Cozy socks and a love note"],
    imagePrompt: "A single, silver hand-bell inside a red Christmas stocking, dramatic spotlight and deep shadows.",
    imageSide: "right",
  },
  {
    id: "q17",
    prompt: "Pick a Christmas job.",
    options: ["Sleigh mechanic", "Mall Santa’s lawyer", "Night watch at the toy factory", "Hot cocoa sommelier"],
    imagePrompt: "A dark, empty toy factory at night, one green light flickering over a mysterious wooden workbench.",
    imageSide: "left",
  },
  {
    id: "q18",
    prompt: "You’re in charge of the holiday playlist. You choose...",
    options: ["Bangers only", "Lo-fi holiday doom", "Whatever makes people nervous", "Classic jazz and slow dances"],
    imagePrompt: "An old vinyl record player spinning a bright red record in a dimly lit, cozy room with holiday decorations.",
    imageSide: "right",
  },
  {
    id: "q19",
    prompt: "The eggnog hits. What happens next?",
    options: ["I host a dance-off", "I nap under the tree", "I start a polite revolution", "I confess my crush"],
    imagePrompt: "A person fast asleep under a heavily decorated Christmas tree, surrounded by fallen tinsel and empty mugs.",
    imageSide: "left",
  },
  {
    id: "q20",
    prompt: "You see a car covered in reindeer antlers. Thoughts?",
    options: ["Iconic, no notes", "Crime, but festive", "A cry for help", "Cute, but I’d rather walk"],
    imagePrompt: "A beat-up old car with large, plush reindeer antlers attached to the windows, driving through a heavy winter blizzard.",
    imageSide: "right",
  },
  {
    id: "q21",
    prompt: "Pick a winter weapon.",
    options: ["Candy cane staff", "Frozen sarcasm", "Icicle spear (decorative)", "A bouquet of candy canes"],
    imagePrompt: "A sharp, jagged icicle held like a dagger, reflecting colorful, blurry Christmas lights in the background.",
    imageSide: "left",
  },
  {
    id: "q22",
    prompt: "Your ideal holiday weather is...",
    options: ["Gentle snow and drama", "Blizzard with perfect visibility", "Apocalyptic, but twinkly", "Light snowfall for a slow stroll"],
    imagePrompt: "A heavy blizzard at night, with a single, brightly lit lamp post and a few twinkling, wind-blown decorations.",
    imageSide: "right",
  },
  {
    id: "q23",
    prompt: "Someone offers you fruitcake. You...",
    options: ["Accept, smile, plot", "Pass it down the line", "Use it as a doorstop", "Share it with someone cute"],
    imagePrompt: "A dense, rock-hard fruitcake being used as a doorstop for a heavy, ancient wooden door, winter light.",
    imageSide: "left",
  },
  {
    id: "q24",
    prompt: "You're asked to say grace before dinner. You...",
    options: ["Go heartfelt and long", "Keep it short and spooky", "Wing it with confidence", "Short, sweet, grateful"],
    imagePrompt: "A long, wooden dinner table set for a holiday feast, with one empty chair and a single lit candle in the center.",
    imageSide: "right",
  },
  {
    id: "q25",
    prompt: "Your holiday drink of choice?",
    options: ["Spiked hot chocolate", "Straight eggnog, no chaser", "Room temperature milk", "Mulled wine and a playlist"],
    imagePrompt: "Three holiday mugs on a snowy windowsill: one steaming with whipped cream, one overflowing with eggnog, one plain milk, dramatic lighting.",
    imageSide: "left",
  },
  {
    id: "q26",
    prompt: "The Elf on the Shelf is watching. You...",
    options: ["Wave menacingly", "Stage an elaborate crime scene", "Pretend you don't see it", "Give it a tiny mug of cocoa"],
    imagePrompt: "An elf doll positioned on a shelf with wide, creepy eyes staring directly at the viewer, surrounded by shadows.",
    imageSide: "right",
  },
  {
    id: "q27",
    prompt: "How do you feel about mistletoe?",
    options: ["Strategic placement expert", "Avoid at all costs", "Weaponize it", "Make a wish and a soft kiss"],
    imagePrompt: "A sprig of mistletoe hanging from a ceiling beam with red ribbons, dramatic shadows, vintage holiday aesthetic.",
    imageSide: "left",
  },
  {
    id: "q28",
    prompt: "Your neighbor's light display is...",
    options: ["Inspirational chaos", "An assault on my retinas", "Amateur hour", "Romantic if you’re walking by"],
    imagePrompt: "A house completely covered in excessive, blinking multicolored Christmas lights, overwhelming and garish, night scene.",
    imageSide: "right",
  },
  {
    id: "q29",
    prompt: "You're stuck assembling a toy at midnight. You...",
    options: ["Follow instructions religiously", "Improvise aggressively", "Accept defeat, order takeout", "Put on music and take my time"],
    imagePrompt: "A frustrated person surrounded by toy parts and confusing instruction manuals on a living room floor at night.",
    imageSide: "left",
  },
  {
    id: "q30",
    prompt: "Pick your holiday conspiracy theory.",
    options: ["Santa is a government drone", "Elves unionized decades ago", "Reindeer can't actually fly", "Santa is just a really good planner"],
    imagePrompt: "A grainy, surveillance-style photo of a sleigh silhouette in the night sky with dramatic conspiracy-style red circles and arrows.",
    imageSide: "right",
  },
  {
    id: "q31",
    prompt: "Someone mentions Black Friday. You...",
    options: ["Eyes light up, battle ready", "Physically recoil", "Online only, like a civilized person", "Only for coffee and people watching"],
    imagePrompt: "A chaotic crowd of shoppers pushing through store doors at dawn, dramatic overhead lighting, motion blur.",
    imageSide: "left",
  },
  {
    id: "q32",
    prompt: "Your ornament breaks. You...",
    options: ["Ceremonial burial", "Sweep it under the tree", "Glue it back with spite", "Save a shard as a memory"],
    imagePrompt: "Shattered glass ornament pieces on a wooden floor, reflecting colorful Christmas lights, melancholic mood.",
    imageSide: "right",
  },
  {
    id: "q33",
    prompt: "The perfect holiday breakfast?",
    options: ["Candy canes and coffee", "Leftover pie, cold", "Nothing, I'm still full from yesterday", "Cinnamon rolls and slow conversation"],
    imagePrompt: "A plate with cold pie and scattered candy canes next to a steaming coffee mug on a morning table.",
    imageSide: "left",
  },
  {
    id: "q34",
    prompt: "You find tinsel in July. You...",
    options: ["Add it to your outfit", "Question everything", "Save it for next year", "Make it a hair accessory"],
    imagePrompt: "A single strand of silver tinsel on a wooden floor in bright summer sunlight streaming through a window.",
    imageSide: "right",
  },
  {
    id: "q35",
    prompt: "Holiday party small talk strategy?",
    options: ["Dominate with stories", "Strategic nodding", "Hide in the kitchen", "Find the dog and vibe"],
    imagePrompt: "A crowded holiday party with people talking in small groups, one person alone by the kitchen doorway, warm lighting.",
    imageSide: "left",
  },
  {
    id: "q36",
    prompt: "Your ideal New Year's Eve?",
    options: ["Public spectacle", "Quiet reflection", "Asleep by 9pm", "Kiss at midnight, then bed"],
    imagePrompt: "A lone person in pajamas on a couch at 8:45pm while fireworks explode outside the window.",
    imageSide: "right",
  },
  {
    id: "q37",
    prompt: "Ugly sweater party approach?",
    options: ["Go ironically beautiful", "Embrace maximum ugly", "Wear a normal sweater, dare them", "Soft knit, cozy, accidentally cute"],
    imagePrompt: "An extremely ugly Christmas sweater with gaudy decorations, blinking lights, and tinsel, displayed on a hanger.",
    imageSide: "left",
  },
  {
    id: "q38",
    prompt: "You're tasked with cookie duty. You...",
    options: ["Bake from scratch, stress bake 40 dozen", "Store bought, premium tier", "Arrange crackers artfully", "Bake a small batch, taste test generously"],
    imagePrompt: "A kitchen counter covered in burnt cookies, fancy store-bought cookies, and plain crackers arranged in a circle.",
    imageSide: "right",
  },
  {
    id: "q39",
    prompt: "Holiday traffic makes you late. You...",
    options: ["Honk rhythmically to carols", "Accept fate, sing along", "Take aggressive shortcuts", "Put on a podcast and chill"],
    imagePrompt: "A line of cars stuck in traffic with Christmas decorations, viewed from above, sunset lighting, endless road.",
    imageSide: "left",
  },
  {
    id: "q40",
    prompt: "The office potluck signup sheet appears. You...",
    options: ["Claim the easy option immediately", "Volunteer for the challenge", "Conveniently miss the deadline", "Bring the signature dip and a smile"],
    imagePrompt: "A clipboard with a potluck signup sheet, most items crossed out, one person's name written in tiny letters.",
    imageSide: "right",
  },
  {
    id: "q41",
    prompt: "A family member asks about your plans. You...",
    options: ["Overshare enthusiastically", "Provide vague updates", "Redirect with questions", "Share the cute version, skip the stress"],
    imagePrompt: "Two people at a holiday table, one talking animatedly, one looking away uncomfortably, warm interior lighting.",
    imageSide: "left",
  },
  {
    id: "q42",
    prompt: "Your signature holiday move?",
    options: ["Aggressive generosity", "Strategic absence", "Chaos coordinator", "Low-key kindness"],
    imagePrompt: "Three wrapped presents: one enormous with excessive bows, one tiny and plain, one unwrapped and chaotic.",
    imageSide: "right",
  },
  {
    id: "q43",
    prompt: "Ice skating plans?",
    options: ["Show off tricks", "Cling to the wall", "Sit in the warming hut", "Hand-hold laps, no falls"],
    imagePrompt: "An outdoor ice skating rink at night with people skating, one person holding onto the wall, twinkling lights.",
    imageSide: "left",
  },
  {
    id: "q44",
    prompt: "You receive a terrible gift. You...",
    options: ["Act like it's perfect", "Honest but kind feedback", "Regift immediately", "Thank them and mean it"],
    imagePrompt: "A person forcing a smile while holding up a truly awful, bizarre Christmas gift, wrapping paper scattered around.",
    imageSide: "right",
  },
  {
    id: "q45",
    prompt: "Holiday baking goes wrong. You...",
    options: ["Serve it anyway with confidence", "Order replacements", "Blame the oven publicly", "Laugh, pour wine, eat it"],
    imagePrompt: "A tray of severely burnt cookies smoking slightly, placed next to the oven, dramatic kitchen lighting.",
    imageSide: "left",
  },
  {
    id: "q46",
    prompt: "The holiday newsletter from that one family. You...",
    options: ["Read every word, take notes", "Skim for drama", "Straight to recycling", "Skim and appreciate the effort"],
    imagePrompt: "A multi-page family newsletter with photos and highlighted text sitting on a table next to a recycling bin.",
    imageSide: "right",
  },
  {
    id: "q47",
    prompt: "Someone suggests caroling. You...",
    options: ["Lead with enthusiasm", "Mumble in the back", "Suddenly remember an appointment", "Join for one song, warm up voice"],
    imagePrompt: "A group of people in winter coats and scarves singing carols on a snowy doorstep, one person backing away.",
    imageSide: "left",
  },
  {
    id: "q48",
    prompt: "Your wrapping paper runs out mid-gift. You...",
    options: ["Creative patchwork", "Newspaper and dignity", "Gift bag, no shame", "Twine and a sprig of pine"],
    imagePrompt: "A half-wrapped present with newspaper covering one end and a gift bag sitting nearby, messy wrapping station.",
    imageSide: "right",
  },
  {
    id: "q49",
    prompt: "Holiday ham or turkey?",
    options: ["Ham, fight me", "Turkey, traditional", "Neither, chaos option", "Veg option, but with gravy"],
    imagePrompt: "A dinner table with both a glazed ham and a roasted turkey, dramatic overhead lighting, family gathering.",
    imageSide: "left",
  },
  {
    id: "q50",
    prompt: "The tree starts leaning. You...",
    options: ["Engineer a solution", "Add more decorations to balance", "Let nature take its course", "Add a cozy blanket base"],
    imagePrompt: "A Christmas tree tilting dangerously to one side, lights and ornaments shifting, living room setting.",
    imageSide: "right",
  },
  {
    id: "q51",
    prompt: "Your holiday spirit animal?",
    options: ["Overcaffeinated reindeer", "Tired snowman", "Feral gingerbread man", "Sleepy golden retriever in a scarf"],
    imagePrompt: "Three Christmas characters side by side: energetic reindeer, melting snowman, gingerbread man with chaotic frosting.",
    imageSide: "left",
  },
  {
    id: "q52",
    prompt: "Gift receipt policy?",
    options: ["Always include, I'm not a monster", "Never, they'll love it", "Passive-aggressive maybe", "Include it with a sweet note"],
    imagePrompt: "A gift with a small receipt taped to it versus one without, side by side comparison, dramatic lighting.",
    imageSide: "right",
  },
  {
    id: "q53",
    prompt: "The fire alarm goes off during dinner. You...",
    options: ["Save the food first", "Grab the presents", "Already outside somehow", "Open windows, keep everyone calm"],
    imagePrompt: "Smoke detector beeping while holiday dinner sits on the table, person frantically grabbing plates, chaotic scene.",
    imageSide: "left",
  },
  {
    id: "q54",
    prompt: "Holiday movie marathon rules?",
    options: ["Classics only, strict order", "Whatever's on, no planning", "Same movie 12 times", "One classic, then a rom-com"],
    imagePrompt: "A couch with blankets and snacks facing a TV screen showing a Christmas movie, cozy evening lighting.",
    imageSide: "right",
  },
  {
    id: "q55",
    prompt: "Someone double-dips in the punch. You...",
    options: ["Call them out immediately", "Mental note, switch to wine", "Join them in solidarity", "Laugh it off, switch cups"],
    imagePrompt: "A festive punch bowl with ladle at a party, someone's hand reaching in suspiciously, overhead view.",
    imageSide: "left",
  },
  {
    id: "q56",
    prompt: "Your holiday hosting style?",
    options: ["Martha Stewart possessed me", "Functional chaos", "Pizza and fairy lights", "Candles, playlists, comfy blankets"],
    imagePrompt: "Three living rooms: one perfect and staged, one messy but festive, one with pizza boxes and twinkle lights.",
    imageSide: "right",
  },
  {
    id: "q57",
    prompt: "White elephant gift strategy?",
    options: ["Thoughtful and clever", "Absolutely useless", "Borderline offensive", "Funny, but kind"],
    imagePrompt: "A pile of white elephant gifts: one nice, one absurd, one questionable, wrapped with varying effort.",
    imageSide: "left",
  },
  {
    id: "q58",
    prompt: "The power goes out Christmas Eve. You...",
    options: ["Candles and stories, embrace it", "Generator deployed immediately", "Panic mildly", "Make cocoa and tell stories"],
    imagePrompt: "A dark living room lit only by candles and fireplace, Christmas tree silhouette in background, cozy but eerie.",
    imageSide: "right",
  },
  {
    id: "q59",
    prompt: "Your relationship with holiday leftovers?",
    options: ["Meal prep champion", "Eat it all immediately", "Forgotten in the back of the fridge", "Grazing plate, all day"],
    imagePrompt: "Refrigerator shelves packed with labeled tupperware containers of holiday leftovers, organized chaos.",
    imageSide: "left",
  },
  {
    id: "q60",
    prompt: "Gingerbread house approach?",
    options: ["Architectural masterpiece", "Abstract art interpretation", "Eat the supplies, skip building", "Team build, snack breaks"],
    imagePrompt: "Three gingerbread houses: one perfect, one collapsed artistically, one just a pile of eaten candy.",
    imageSide: "right",
  },
  {
    id: "q61",
    prompt: "Holiday shopping procrastination level?",
    options: ["Done in October", "December 24th, 11pm", "Gift cards only", "Shopping with a warm drink, no rush"],
    imagePrompt: "A calendar showing December 24th with a panicked person on a laptop doing last-minute online shopping at night.",
    imageSide: "left",
  },
  {
    id: "q62",
    prompt: "The advent calendar chocolate melted. You...",
    options: ["Eat it anyway", "Artistic chocolate puddle", "Demand a refund", "Stir it into a latte"],
    imagePrompt: "An advent calendar with melted chocolate seeping out of opened doors, messy and slightly sad.",
    imageSide: "right",
  },
  {
    id: "q63",
    prompt: "Your opinion on inflatable lawn decorations?",
    options: ["More is more", "Tasteful minimalism only", "They're all cursed", "One tasteful one, for the vibes"],
    imagePrompt: "A yard with excessive inflatable Christmas decorations, some deflated, some fighting the wind, chaotic suburban scene.",
    imageSide: "left",
  },
  {
    id: "q64",
    prompt: "The WiFi goes down during a holiday Zoom. You...",
    options: ["Aggressive router reset", "Pretend it's still working", "Freedom at last", "Call them and keep it cozy"],
    imagePrompt: "A laptop screen showing a frozen Zoom call with multiple family members' confused faces, router blinking in background.",
    imageSide: "right",
  },
  {
    id: "q65",
    prompt: "Holiday pajamas: yay or nay?",
    options: ["Matching set, enforced", "Ironically yes", "Absolutely not", "Soft set, maybe matching"],
    imagePrompt: "A family in matching festive pajamas posed awkwardly for a photo, various levels of enthusiasm visible.",
    imageSide: "left",
  },
  {
    id: "q66",
    prompt: "The store is out of your planned gift. You...",
    options: ["Upgrade dramatically", "Pivot to something completely different", "Give cash, cry inside", "Give a cozy experience instead"],
    imagePrompt: "Empty store shelves with one lonely item remaining, a shopper staring in disbelief, holiday sale signs.",
    imageSide: "right",
  },
  {
    id: "q67",
    prompt: "Your take on holiday tipping?",
    options: ["Generous to a fault", "Standard but thoughtful", "What tipping?", "A little extra and a card"],
    imagePrompt: "Various holiday cards with money sticking out, envelopes addressed to delivery drivers, mail carriers, doormen.",
    imageSide: "left",
  },
  {
    id: "q68",
    prompt: "Someone regifts to you (and you know it). You...",
    options: ["Call them out with receipts", "Regift it back next year", "Actually thrilled, free stuff", "Smile and use it happily"],
    imagePrompt: "A wrapped gift with the previous gift tag partially scratched out and a new name written over it.",
    imageSide: "right",
  },
  {
    id: "q69",
    prompt: "Holiday card photo shoot vibe?",
    options: ["Professional photographer, multiple outfits", "iPhone timer, take 47", "No photo, just a heartfelt note", "Candid shot with cocoa"],
    imagePrompt: "A family attempting a holiday card photo, one person blinking, one person looking away, chaos captured.",
    imageSide: "left",
  },
  {
    id: "q70",
    prompt: "The tree topper won't stay on. You...",
    options: ["Engineering degree activated", "Duct tape and prayer", "No topper needed", "Tie a ribbon and call it art"],
    imagePrompt: "A crooked star on top of a Christmas tree held up with visible duct tape, slightly comedic angle.",
    imageSide: "right",
  },
  {
    id: "q71",
    prompt: "Holiday work party attendance?",
    options: ["First to arrive, last to leave", "Show face, strategic exit", "Sudden illness", "Show up for the dessert table"],
    imagePrompt: "An office holiday party in full swing, one person sneaking toward the exit, festive decorations everywhere.",
    imageSide: "left",
  },
  {
    id: "q72",
    prompt: "Your New Year's resolution?",
    options: ["Ambitious and specific", "Vague and achievable", "Same as last year (unstarted)", "More walks, more naps"],
    imagePrompt: "A notebook with New Year's resolutions written and crossed out repeatedly, coffee stain, realistic texture.",
    imageSide: "right",
  },
];

export const QUESTIONS_BY_ID = new Map(QUESTIONS.map((question) => [question.id, question]));
