import type { XmasQuestion } from "@/types/game";

export const QUESTIONS: XmasQuestion[] = [
  {
    id: "q1",
    prompt: "You show up to the holiday party already late. What is your excuse?",
    options: ["Stuck in a chimney crawlspace", "Got lost in a mall parking lot", "I was busy saving a reindeer"],
    imagePrompt: "A person in a Santa suit stuck halfway down a brick chimney, legs kicking in the air, comic book style, cozy winter night lighting.",
    imageSide: "left",
  },
  {
    id: "q2",
    prompt: "Pick your preferred holiday snack.",
    options: ["Peppermint bark with attitude", "A suspiciously festive fruitcake", "Cold pizza in a Santa hat"],
    imagePrompt: "A suspiciously glowing, dense fruitcake with small festive decorations, moody dramatic lighting, hand-drawn illustration style.",
    imageSide: "right",
  },
  {
    id: "q3",
    prompt: "Your gift wrapping style is best described as...",
    options: ["Beautiful chaos and tape", "Minimalist, borderline threatening", "I don’t wrap. I haunt."],
    imagePrompt: "A gift wrapped in way too much tape and mismatched colorful paper, chaotic but festive, hand-drawn Peanuts-style illustration.",
    imageSide: "left",
  },
  {
    id: "q4",
    prompt: "Someone puts on carols. Your move?",
    options: ["Sing too loud on purpose", "Lip sync and judge quietly", "Swap it for ominous bells"],
    imagePrompt: "A pair of large, antique brass church bells hanging in a snowy belfry at night, dramatic shadows, winter atmosphere.",
    imageSide: "right",
  },
  {
    id: "q5",
    prompt: "You find a list labeled ‘Naughty.’ What do you do?",
    options: ["Update it with receipts", "Pretend you never saw it", "Add my own name for sport"],
    imagePrompt: "A thick parchment scroll labeled 'NAUGHTY' in big red letters, lying on a wooden table next to a flickering candle and a quill.",
    imageSide: "left",
  },
  {
    id: "q6",
    prompt: "Choose your holiday transportation.",
    options: ["Sleigh with questionable safety", "Snowmobile with fake antlers", "Public transit, but it’s haunted"],
    imagePrompt: "A vintage red sleigh with mismatched wooden planks and a loose runner, sitting alone in deep snow under a moonlit sky.",
    imageSide: "right",
  },
  {
    id: "q7",
    prompt: "What’s your role in group photo time?",
    options: ["Center stage, obviously", "Side-eye in the back row", "Photobomb from the shadows"],
    imagePrompt: "A group of festive people posing for a photo, with one person as a mysterious shadowy figure with glowing eyes in the back row.",
    imageSide: "left",
  },
  {
    id: "q8",
    prompt: "A child asks if you’re Santa. You reply…",
    options: ["Ho ho... maybe", "Absolutely not, move along", "I’m Santa’s HR"],
    imagePrompt: "A small child looking up in awe at a person in a corporate suit wearing a tiny, crooked Santa hat, high contrast lighting.",
    imageSide: "right",
  },
  {
    id: "q9",
    prompt: "Pick a holiday smell.",
    options: ["Cinnamon, pine, mild panic", "Burnt sugar and regret", "Wet wool and mystery"],
    imagePrompt: "A steaming mug of spiced cider sitting next to a pile of wet, woolly mittens on a rustic wooden bench.",
    imageSide: "left",
  },
  {
    id: "q10",
    prompt: "You’ve been tasked with decorating the tree. You...",
    options: ["Create a glitter explosion", "Hang one ornament and leave", "Replace the star with a skull"],
    imagePrompt: "A Christmas tree where the top star has been replaced by a small, festive, white skull, twinkling lights in the background.",
    imageSide: "right",
  },
  {
    id: "q11",
    prompt: "The office Secret Santa is happening. Your strategy?",
    options: ["Overdeliver, become legend", "Regift like a pro", "Forget the date, improvise"],
    imagePrompt: "A poorly wrapped box with a 'To: Secret Santa' tag, sitting lonely on a messy office desk after everyone has left.",
    imageSide: "left",
  },
  {
    id: "q12",
    prompt: "Which holiday movie energy do you embody?",
    options: ["Chaotic heartwarming montage", "Brooding misunderstood villain", "Animated chaos with a moral"],
    imagePrompt: "A split-screen view: one side shows a heartwarming cozy fireplace, the other shows a brooding figure in a dark holiday cloak.",
    imageSide: "right",
  },
  {
    id: "q13",
    prompt: "Pick a holiday pet.",
    options: ["Reindeer with attitude", "Overcaffeinated elf dog", "Silent snow owl"],
    imagePrompt: "A majestic snow owl with a tiny red scarf perched on a frosted pine branch, soft winter snowflakes falling.",
    imageSide: "left",
  },
  {
    id: "q14",
    prompt: "A snowball fight breaks out. You...",
    options: ["Lead the charge", "Build a tactical fort", "Disappear, reappear elsewhere"],
    imagePrompt: "A massive, tactical snow fort with multiple levels and a flag made from an old holiday sweater.",
    imageSide: "right",
  },
  {
    id: "q15",
    prompt: "Someone says ‘holiday cheer.’ Your reaction?",
    options: ["Pour it into a mug", "Nod politely", "Ask for a refund"],
    imagePrompt: "An empty glass mug with a few drops of eggnog and a single peppermint stick leaning against the rim, lonely setting.",
    imageSide: "left",
  },
  {
    id: "q16",
    prompt: "Your stocking is filled with...",
    options: ["Glitter, snacks, chaos", "A single ominous bell", "A note that just says ‘soon’"],
    imagePrompt: "A single, silver hand-bell inside a red Christmas stocking, dramatic spotlight and deep shadows.",
    imageSide: "right",
  },
  {
    id: "q17",
    prompt: "Pick a Christmas job.",
    options: ["Sleigh mechanic", "Mall Santa’s lawyer", "Night watch at the toy factory"],
    imagePrompt: "A dark, empty toy factory at night, one green light flickering over a mysterious wooden workbench.",
    imageSide: "left",
  },
  {
    id: "q18",
    prompt: "You’re in charge of the holiday playlist. You choose...",
    options: ["Bangers only", "Lo-fi holiday doom", "Whatever makes people nervous"],
    imagePrompt: "An old vinyl record player spinning a bright red record in a dimly lit, cozy room with holiday decorations.",
    imageSide: "right",
  },
  {
    id: "q19",
    prompt: "The eggnog hits. What happens next?",
    options: ["I host a dance-off", "I nap under the tree", "I start a polite revolution"],
    imagePrompt: "A person fast asleep under a heavily decorated Christmas tree, surrounded by fallen tinsel and empty mugs.",
    imageSide: "left",
  },
  {
    id: "q20",
    prompt: "You see a car covered in reindeer antlers. Thoughts?",
    options: ["Iconic, no notes", "Crime, but festive", "A cry for help"],
    imagePrompt: "A beat-up old car with large, plush reindeer antlers attached to the windows, driving through a heavy winter blizzard.",
    imageSide: "right",
  },
  {
    id: "q21",
    prompt: "Pick a winter weapon.",
    options: ["Candy cane staff", "Frozen sarcasm", "Icicle spear (decorative)"],
    imagePrompt: "A sharp, jagged icicle held like a dagger, reflecting colorful, blurry Christmas lights in the background.",
    imageSide: "left",
  },
  {
    id: "q22",
    prompt: "Your ideal holiday weather is...",
    options: ["Gentle snow and drama", "Blizzard with perfect visibility", "Apocalyptic, but twinkly"],
    imagePrompt: "A heavy blizzard at night, with a single, brightly lit lamp post and a few twinkling, wind-blown decorations.",
    imageSide: "right",
  },
  {
    id: "q23",
    prompt: "Someone offers you fruitcake. You...",
    options: ["Accept, smile, plot", "Pass it down the line", "Use it as a doorstop"],
    imagePrompt: "A dense, rock-hard fruitcake being used as a doorstop for a heavy, ancient wooden door, winter light.",
    imageSide: "left",
  },
  {
    id: "q24",
    prompt: "You’re asked to say grace before dinner. You...",
    options: ["Go heartfelt and long", "Keep it short and spooky", "Wing it with confidence"],
    imagePrompt: "A long, wooden dinner table set for a holiday feast, with one empty chair and a single lit candle in the center.",
    imageSide: "right",
  },
];

export const QUESTIONS_BY_ID = new Map(QUESTIONS.map((question) => [question.id, question]));
