export const CHARACTERS = [
  "Santa Claus",
  "Mall Santa",
  "Rudolph",
  "Non-Rudolph Reindeer",
  "The Grinch",
  "Krampus",
  "Frosty the Snowman",
  "Charlie Brown",
  "Polar Bear",
  "Orphan From a Christmas Movie",
  "Blow-Up Inflatable Santa",
  "Jesus",
  "Baby Jesus",
  "Jesus Dressed as Santa",
  "Elf Union Organizer",
  "The Mistletoe Menace",
  "The Tree on the Roof of the Car",
  "The Uninvited Caroler",
  "The Eggnog Alchemist",
  "The Gift Receipt Goblin",
  "The Sleigh Mechanic",
  "The Haunted Nutcracker",
  "The Last-Minute Shopper",
  "The Snow Day Extrovert",
  "The Holiday Ghost Who Means Well",
];
